/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef call_CONSTANTS_H
#define call_CONSTANTS_H

#include "call_types.h"

namespace com { namespace seafooler { namespace project {

class callConstants {
 public:
  callConstants();

};

extern const callConstants g_call_constants;

}}} // namespace

#endif
