/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "call_constants.h"

namespace com { namespace seafooler { namespace project {

const callConstants g_call_constants;

callConstants::callConstants() {
}

}}} // namespace

