/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef callThrift_H
#define callThrift_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "call_types.h"

namespace com { namespace seafooler { namespace project {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class callThriftIf {
 public:
  virtual ~callThriftIf() {}
  virtual void CallFunc(std::string& _return, const std::string& funcname, const std::string& input) = 0;
};

class callThriftIfFactory {
 public:
  typedef callThriftIf Handler;

  virtual ~callThriftIfFactory() {}

  virtual callThriftIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(callThriftIf* /* handler */) = 0;
};

class callThriftIfSingletonFactory : virtual public callThriftIfFactory {
 public:
  callThriftIfSingletonFactory(const boost::shared_ptr<callThriftIf>& iface) : iface_(iface) {}
  virtual ~callThriftIfSingletonFactory() {}

  virtual callThriftIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(callThriftIf* /* handler */) {}

 protected:
  boost::shared_ptr<callThriftIf> iface_;
};

class callThriftNull : virtual public callThriftIf {
 public:
  virtual ~callThriftNull() {}
  void CallFunc(std::string& /* _return */, const std::string& /* funcname */, const std::string& /* input */) {
    return;
  }
};

typedef struct _callThrift_CallFunc_args__isset {
  _callThrift_CallFunc_args__isset() : funcname(false), input(false) {}
  bool funcname :1;
  bool input :1;
} _callThrift_CallFunc_args__isset;

class callThrift_CallFunc_args {
 public:

  callThrift_CallFunc_args(const callThrift_CallFunc_args&);
  callThrift_CallFunc_args& operator=(const callThrift_CallFunc_args&);
  callThrift_CallFunc_args() : funcname(), input() {
  }

  virtual ~callThrift_CallFunc_args() throw();
  std::string funcname;
  std::string input;

  _callThrift_CallFunc_args__isset __isset;

  void __set_funcname(const std::string& val);

  void __set_input(const std::string& val);

  bool operator == (const callThrift_CallFunc_args & rhs) const
  {
    if (!(funcname == rhs.funcname))
      return false;
    if (!(input == rhs.input))
      return false;
    return true;
  }
  bool operator != (const callThrift_CallFunc_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const callThrift_CallFunc_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class callThrift_CallFunc_pargs {
 public:


  virtual ~callThrift_CallFunc_pargs() throw();
  const std::string* funcname;
  const std::string* input;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _callThrift_CallFunc_result__isset {
  _callThrift_CallFunc_result__isset() : success(false) {}
  bool success :1;
} _callThrift_CallFunc_result__isset;

class callThrift_CallFunc_result {
 public:

  callThrift_CallFunc_result(const callThrift_CallFunc_result&);
  callThrift_CallFunc_result& operator=(const callThrift_CallFunc_result&);
  callThrift_CallFunc_result() : success() {
  }

  virtual ~callThrift_CallFunc_result() throw();
  std::string success;

  _callThrift_CallFunc_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const callThrift_CallFunc_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const callThrift_CallFunc_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const callThrift_CallFunc_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _callThrift_CallFunc_presult__isset {
  _callThrift_CallFunc_presult__isset() : success(false) {}
  bool success :1;
} _callThrift_CallFunc_presult__isset;

class callThrift_CallFunc_presult {
 public:


  virtual ~callThrift_CallFunc_presult() throw();
  std::string* success;

  _callThrift_CallFunc_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class callThriftClient : virtual public callThriftIf {
 public:
  callThriftClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  callThriftClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void CallFunc(std::string& _return, const std::string& funcname, const std::string& input);
  void send_CallFunc(const std::string& funcname, const std::string& input);
  void recv_CallFunc(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class callThriftProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<callThriftIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (callThriftProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_CallFunc(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  callThriftProcessor(boost::shared_ptr<callThriftIf> iface) :
    iface_(iface) {
    processMap_["CallFunc"] = &callThriftProcessor::process_CallFunc;
  }

  virtual ~callThriftProcessor() {}
};

class callThriftProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  callThriftProcessorFactory(const ::boost::shared_ptr< callThriftIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< callThriftIfFactory > handlerFactory_;
};

class callThriftMultiface : virtual public callThriftIf {
 public:
  callThriftMultiface(std::vector<boost::shared_ptr<callThriftIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~callThriftMultiface() {}
 protected:
  std::vector<boost::shared_ptr<callThriftIf> > ifaces_;
  callThriftMultiface() {}
  void add(boost::shared_ptr<callThriftIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void CallFunc(std::string& _return, const std::string& funcname, const std::string& input) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->CallFunc(_return, funcname, input);
    }
    ifaces_[i]->CallFunc(_return, funcname, input);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class callThriftConcurrentClient : virtual public callThriftIf {
 public:
  callThriftConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  callThriftConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void CallFunc(std::string& _return, const std::string& funcname, const std::string& input);
  int32_t send_CallFunc(const std::string& funcname, const std::string& input);
  void recv_CallFunc(std::string& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

}}} // namespace

#endif
